### ISSUE TITLE
Dialog Extension can hang NetLogo

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/Dialog-Extension#1]
These two progams compile, but NetLogo hangs when the setup procedure is run.
This was on a Mac and I needed to use the Activity Monitor to close NetLogo.

```
extensions [dialog]
globals [ fave ]
to setup
  dialog:user-one-of "What's your favorite number?" [1 2 3]
  [result -> set fave result]
end
```

```
extensions [dialog]
to setup
  crt 4
  dialog:user-one-of "What's your favorite number?" [1 2 3]
  [result -> ask turtles [fd 10 * result]]
end
```

**Comment by TheBizzle** [comment]
Aaron and I looked into this.  Our minimum reproducible example was:

```
extensions [dialog]
to setup
  dialog:user-message "?" [crt 1]
end
```

The issue is that `onComplete.perform(context, Array(result))` needs to be run on the job thread, not on the event thread.  But I believe that popping up the dialogs before that line of code *does* still need to happen on the event thread.
